export type StorefrontCategoryDef = {
  slug: string;
  nameKey: "cat.body" | "cat.filters" | "cat.brakes" | "cat.engine" | "cat.suspension" | "cat.clutch" | "cat.electricals" | "cat.lubricants";
  descKey:
    | "cat.bodyDesc"
    | "cat.filtersDesc"
    | "cat.brakesDesc"
    | "cat.engineDesc"
    | "cat.suspensionDesc"
    | "cat.clutchDesc"
    | "cat.electricalsDesc"
    | "cat.lubricantsDesc";
  /**
   * The ORIGIN file, 1024x1024, with a lot of empty canvas around the actual
   * products - measured 33% to 100% content fill. Kept, because it is the
   * editable original and admin references it by path.
   */
  image: string;
  /**
   * The tightly-framed DERIVATIVE of `image`, generated by
   * `scripts/frame-category-images.mjs`. This is what the storefront renders.
   *
   * WHY A SEPARATE FILE RATHER THAN A CSS CROP. The sources are the editable
   * originals, and a crop baked into them is invisible in a file browser and
   * cannot be undone. A derivative is additive: delete it and the previous
   * appearance returns exactly. It is also content-aware - the frame is the
   * detected extent of the product plus a 3% margin - not a fixed percentage,
   * so a tile that already fills its canvas is left alone.
   *
   * Regenerate with `npm run frame:category-images`.
   */
  framedImage: string;
  sourceSlugs: string[];
};

/** The framed path for a category source path, derived not hard-coded. */
export function framedCategoryImage(sourcePath: string): string {
  return sourcePath.replace(
    /\/images\/category\/(.+)\.(png|jpe?g|webp)$/i,
    "/images/category/framed/$1.webp",
  );
}

export const STOREFRONT_CATEGORIES: StorefrontCategoryDef[] = [
  {
    slug: "body-parts",
    nameKey: "cat.body",
    descKey: "cat.bodyDesc",
    image: "/images/category/body-parts.png",
    framedImage: "/images/category/framed/body-parts.webp",
    sourceSlugs: [
      "outside-door-handle",
      "window-regulator-assy",
      "side-view-mirror",
      "inside-door-handle",
      "door-latch-assy",
      "sub-mirror",
      "fuel-tank-cap",
      "window-regulator-handles",
      "door-hinges",
      "door-striker",
      "bonnet-lock",
      "power-window-switches",
      "window-lock",
      "front-grills",
      "glove-box-dash-board-locks",
      "door-lock-w-keys",
      "dickey-shocker-gas-springs",
      "bumper-brackets",
      "seat-belts",
      "roof-handle",
      "seat-recliners",
      "door-lock-kit",
      "door-lock-knob",
      "door-stopper",
      "fuel-tank-neck",
      "fog-lamp-cover",
      "dala-handles",
      "bonnet-hinges",
      "ratchet-tie-down",
      "wiper-linkage",
      "arm-rest-handle",
      "stepney-brackets",
      "dickey-trunklid-locks",
      "grab-handle",
      "side-mirror-bracket",
      "fender-linings",
      "sash",
      "quarter-glass-frame",
      "bonnet-handle",
      "license-number-plates",
      "door-lock",
      "mud-guard-flap",
      "inner-pull-handle",
      "foot-step",
      "wiper-arm",
      "bumper-corners",
      "sunvisor",
      "head-light-bezel",
      "inside-mirror",
      "bonnet-opener",
      "wheel-cap",
      "side-mirror-rods",
      "sunshade-bracket",
      "body",
      "fuel-tank-locks",
      "wiper-blade",
      "channels-guide-rails",
    ],
  },
  {
    slug: "filters",
    nameKey: "cat.filters",
    descKey: "cat.filtersDesc",
    image: "/images/category/filters.png",
    framedImage: "/images/category/framed/filters.webp",
    sourceSlugs: ["filters-cat-src-filters", "filters"],
  },
  {
    slug: "braking-system",
    nameKey: "cat.brakes",
    descKey: "cat.brakesDesc",
    image: "/images/category/braking-system.png",
    framedImage: "/images/category/framed/braking-system.webp",
    sourceSlugs: ["brake-shoes", "brake-linings", "brake-fluid", "brakes"],
  },
  {
    slug: "engine-parts",
    nameKey: "cat.engine",
    descKey: "cat.engineDesc",
    image: "/images/category/engine-parts.png",
    framedImage: "/images/category/framed/engine-parts.webp",
    sourceSlugs: [
      "engine",
      "radiator-cap",
      "cooling",
      "fan",
      "sensor",
      "hand-throttle",
      "accelerator-pedal",
      "urea-adblue-tank-cap",
    ],
  },
  {
    slug: "suspension-steering",
    nameKey: "cat.suspension",
    descKey: "cat.suspensionDesc",
    image: "/images/category/suspension-steering.png",
    framedImage: "/images/category/framed/suspension-steering.webp",
    sourceSlugs: [
      "shock-absorbers-shockers",
      "steering-wheels",
      "springs",
      "linkage-rod",
      "rods",
      "suspension",
    ],
  },
  {
    slug: "clutch-transmission",
    nameKey: "cat.clutch",
    descKey: "cat.clutchDesc",
    image: "/images/category/clutch-transmission.png",
    framedImage: "/images/category/framed/clutch-transmission.webp",
    sourceSlugs: ["gear-lever-knobs", "gear-lever-boot", "transmission"],
  },
  {
    slug: "electricals",
    nameKey: "cat.electricals",
    descKey: "cat.electricalsDesc",
    image: "/images/category/electricals.png",
    framedImage: "/images/category/framed/electricals.webp",
    sourceSlugs: [
      "cables-wires",
      "switches",
      "horns",
      "motors",
      "battery-terminals",
      "relay",
      "connector",
      "head-lights",
      "fog-lamp",
      "meter",
      "electrical",
    ],
  },
  {
    slug: "lubricants",
    nameKey: "cat.lubricants",
    descKey: "cat.lubricantsDesc",
    image: "/images/category/lubricants.png",
    framedImage: "/images/category/framed/lubricants.webp",
    sourceSlugs: [
      "greases",
      "diesel-engine-oils",
      "gear-oils",
      "motorbike-oils",
      "passenger-car-engine-oils",
      "cng-engine-oils",
      "agriculture-tractor-oils",
      "mini-cv-engine-oils",
      "hydraulic-oil",
      "coolant",
      "diesel-exhaust-fluid",
      "rust-preventive-oil",
      "diesel-engine-oil",
      "metal-working-fluid",
      "rock-drill-oil",
      "circulating-oil",
      "gear-oil",
      "spinning-oil",
      "quenching-oil",
      "compressor-oil",
      "refrigeration-oil",
      "thermic-fluid",
      "special-grade-machinery-oil",
      "axle-transmission-oil",
    ],
  },
];

const bySlug = new Map(STOREFRONT_CATEGORIES.map((item) => [item.slug, item]));

const sourceToStorefront = new Map<string, string>();
for (const item of STOREFRONT_CATEGORIES) {
  for (const source of item.sourceSlugs) {
    sourceToStorefront.set(source, item.slug);
  }
}

export function findStorefrontCategory(slug: string): StorefrontCategoryDef | null {
  const key = slug.trim().toLowerCase();
  return bySlug.get(key) ?? null;
}

export function storefrontSlugForSourceCategory(sourceSlug: string): string | null {
  return sourceToStorefront.get(sourceSlug.trim().toLowerCase()) ?? null;
}

export function typesenseCategoryFilter(names: string[]): string | null {
  const values = [...new Set(names.map((name) => name.trim()).filter(Boolean))];
  if (!values.length) return null;
  return `category:=[${values.map((name) => `\`${name.replaceAll("`", "")}\``).join(",")}]`;
}
